name: build
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build FFmpeg
      shell: cmd
      run: |
        git clone "https://github.com/laggykiller/vcpkg.git"
        cd vcpkg
        git checkout f78487adad635f529b4e2b5fcb4fe4f4b08c4deb
        call bootstrap-vcpkg.bat
        cd ..
        "vcpkg\vcpkg.exe" install --triplet=x64-windows-static-release
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg
        path: ./vcpkg_installed/x64-windows-static-release/*